<?php

namespace AppBundle\Repository\Admin\Pages;

use AppBundle\Repository\RepositoryTrait;

/**
 * MaintenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaintenanceRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
