<?php

namespace AppBundle\Repository\Admin\Pages;

use AppBundle\Repository\RepositoryTrait;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
