home:
    path: /
    defaults: { _controller: AppBundle:Front\Content\Content:index }
    
###
# Category
###

## Affichage de toutes les offres d'une category
user_partner_company_offre_category:
    path: /categories/{slug}
    defaults: { _controller: AppBundle:Front\Content\Content:showSingleCategory }

###
# Offre
###

## Affichage d'une offre    
user_partner_company_offre_single:
    path: /offres/{slug}
    defaults: { _controller: AppBundle:Front\Content\Content:showSingleOffre }