    
###
# Payment
###
payment:
    resource: "@AppBundle/Resources/config/routing/front/payment/payment.yml"
    prefix: /payment
    
###
# Order
###
carte_order:
    resource: "@AppBundle/Resources/config/routing/front/payment/order_carte.yml"
    prefix: /orders/carte