carte_order_new:
    path: /{carte}
    defaults: { _controller: AppBundle:Payment\OrderCarte:new }
    methods: [GET]    
    
carte_order_show:
    path: /{order}/show
    defaults: { _controller: AppBundle:Payment\OrderCarte:show }    
    methods: [GET,POST]    
    
carte_order_payment_create:
    path: /{order}/payment-create
    defaults: { _controller: AppBundle:Payment\OrderCarte:paymentCreate }    
    
#carte_order_payment_complete:
#    path: /{order}/payment-complete
#    defaults: { _controller: AppBundle:Payment\OrderCarte:paymentComplete } 
#    
#carte_order_payment_cancel:
#    path: /{order}/payment-cancel
#    defaults: { _controller: AppBundle:Payment\OrderCarte:paymentCancel }     