return_payment:
    path: /return/{order}
    defaults: { _controller: AppBundle:Payment\Payment:returnPayment }
    methods: [GET]    
    
cancel_payment:
    path: /cancel/{order}
    defaults: { _controller: AppBundle:Payment\Payment:cancelPayment }    
    methods: [GET] 
    
notify_payment:
    path: /notify/{order}
    defaults: { _controller: AppBundle:Payment\Payment:notifyPayment }    
    methods: [GET]     