parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: nofiplus
    database_user: root
    database_password: Bismillah
    mailer_transport: mail
    mailer_host: auth.smtp.1and1.fr
    mailer_user: contact@nofiplus.com
    mailer_from_name: 'NOFI+'
    mailer_password: #nofiplus2018
    mailer_encryption: 'ssl'
    mailer_port: 465
    mailer_auth_mode: 'login'
