app:
    resource: "@AppBundle/Resources/config/routing/all.yml"

easyadmin:
    path: /dashboard
    defaults: { _controller: EasyAdminBundle:Admin:index }
    
admin:
    path: /dashboard
    defaults: { _controller: EasyAdminBundle:Admin:index }    

    
