# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
acl:
        connection: default
security:

#    acl:
#        connection: default
        
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PARTNER]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _switch_user }
            logout_on_user_change: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:       true
            anonymous:    true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/register/(abonne|partner)/confirm*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, allow_if: "! is_authenticated()" }
        - { path: ^/resetting,  allow_if: "is_anonymous()" }
        - { path: ^/partners/, roles: ROLE_PARTNER }
        - { path: ^/orders/carte/new, roles: ROLE_USER }
        - { path: ^/orders/carte/show, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_ADMIN }