<?php

namespace AppBundle\Repository\User\Abonne;

use AppBundle\Repository\RepositoryTrait;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
