security:
    resource: "@AppBundle/Resources/config/routing/front/security.yml"


    
registration:
    resource: "@AppBundle/Resources/config/routing/front/registration.yml"
    prefix: /register
    
resetting:
    resource: "@AppBundle/Resources/config/routing/front/resetting.yml"
    prefix: /resetting
    
change_password.xml:
    resource: "@AppBundle/Resources/config/routing/front/change_password.yml"
    prefix: /profile    
    
partner:
    resource: "@AppBundle/Resources/config/routing/front/partner/all.yml"
    prefix: /partners       
    
abonne:
    resource: "@AppBundle/Resources/config/routing/front/abonne/all.yml"
    prefix: /abonnes
    
    
###
# Payment and Orders
###
payment:
    resource: "@AppBundle/Resources/config/routing/front/payment/all.yml"
    
###
# Pages
###
pages:
    resource: "@AppBundle/Resources/config/routing/front/pages/all.yml"
    prefix: /pages    
    
###
# Content
###
content:
    resource: "@AppBundle/Resources/config/routing/front/content/all.yml"