fos_user_registration_register:
    path: /{asuser}
    defaults: 
        _controller: AppBundle:Front\Registration:register
        asuser: 'abonne'
    methods: [GET, POST]
    requirements:
        asuser: abonne|partner
    
fos_user_registration_check_email:
    path: /{asuser}/check-email 
    defaults: 
        _controller: AppBundle:Front\Registration:checkEmail 
        asuser: 'abonne'
    methods: [GET]
    requirements:
        asuser: abonne|partner

fos_user_registration_confirm:
    path: /{asuser}/confirm/{token} 
    defaults: 
        _controller: AppBundle:Front\Registration:confirm 
        asuser: 'abonne'
    methods: [GET]
    requirements:
        asuser: abonne|partner

fos_user_registration_confirmed:
    path: /{asuser}/confirmed
    defaults: 
        _controller: AppBundle:Front\Registration:confirmed 
        asuser: 'abonne'
    methods: [GET]
    requirements:
        asuser: abonne|partner