home:
    path: /
    defaults: { _controller: AppBundle:Default:index }

###
# ADMIN
###
admin:
    resource: "@AppBundle/Resources/config/routing/admin/all.yml"
    prefix: /admin 

###
# FRONT
###
front:
    resource: "@AppBundle/Resources/config/routing/front/all.yml"
    
###
# Payment and Orders
###
payment:
    resource: "@AppBundle/Resources/config/routing/front/payment/all.yml"
    
###
# Pages
###
pages:
    resource: "@AppBundle/Resources/config/routing/front/pages/all.yml"
    prefix: /pages