<?php

namespace AppBundle\Repository\Admin\HowEnjoy;

use AppBundle\Repository\RepositoryTrait;

/**
 * HowEnjoyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HowEnjoyRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
