<?php

namespace AppBundle\Repository\Payment;

use AppBundle\Repository\RepositoryTrait;

/**
 * CarteOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteOrderRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
