# config/routin/admin/all.yml

###
# Home admin
###
admin_home:
    path: /
    defaults: { _controller: AppBundle:Admin\Index:index }
    
###
# Category
###
admin_category:
    resource: "@AppBundle/Resources/config/routing/admin/category/all.yml"
    prefix: /category
    
###
# How Enjoy
###
admin_how_enjoy:
    resource: "@AppBundle/Resources/config/routing/admin/how_enjoy/all.yml"
    prefix: /how-enjoy