# Easy Admin Bundle   
easy_admin:
    design:
        menu:
            # Pages
            - { label: 'Pages' }
            - { entity: 'Pages', label: 'Pages' }
            - { entity: 'Maintenance', label: 'Maintenance mode' }
    entities:     
        Pages:
            class: AppBundle\Entity\Admin\Pages\Page
            label: Pages
            list:
                fields: ['id', 'title', 'label', 'uniqueStringId', 'createdAt', deletedAt']
            form:
                fields:
                    - { property: title, label: 'Titre de la page' }
                    - { property: label, help: 'Label du menu dans le front' }
                    - { property: uniqueStringId, type: choice, type_options: {choices: {'Laisser vide': '', Contact: contact, CGV: cgv, 'Mentions légales': 'mentions-legales'} }, label: 'Type de page' }
                    - createdAt
                    #- { property: locale, type: locale, type_options: {required: true}, label: 'Langue de la page' }
                    - { property: content, trans: true, type: ckeditor }
        Maintenance:
            class: AppBundle\Entity\Admin\Pages\Maintenance
            list:
                fields: ['id', 'enable', 'title', 'createdAt', deletedAt']
            form:
                fields:
                    - { property: title, label: 'Titre de la page' }
                    - enable
                    #- { property: locale, type: locale }
                    - { property: content, trans: true, type: ckeditor }