# Easy Admin Bundle   
easy_admin:
    design:
        menu:
            # Users
            - { label: 'Users' }
            - label: 'Abonne'
              children:
                - { entity: 'Abonne', label: 'Abonnes' }
                - { entity: Carte, label: 'Cartes' }
                - label: Commandes
                - { entity: OrderCarte, label: Commandes }
                - { entity: PaymentInstruction, label: 'Instruction de paiement' }
                #- { entity: Payment, label: Paiement }
            - label: 'Partners'
              children:
                - { entity: 'Partner', label: 'Partenaires' }
                - { entity: Company, label: Entreprises }
                - { entity: Offre, label: Offres }
            - label: 'Admin'
              children:
                - { entity: 'Admin', label: 'Admins' }
    entities:
        ###
        # Abonne
        ###
        Abonne:
            class: AppBundle\Entity\User\Abonne\Abonne
            disabled_actions: ['new','delete']
            list: 
                fields: [id, username, email, enabled, enabledByAdmin, lastLogin]
        Carte:
            class: AppBundle\Entity\User\Abonne\Carte
            disabled_actions: ['new','delete']
            list: 
                fields: 
                    - id
                    - number
                    - start 
                    - end 
                    - user
                    - category
                    - order
        OrderCarte:
            class: AppBundle\Entity\Payment\OrderCarte
            disabled_actions: ['new','delete']
            list:
                fields:
                    - id 
                    - amount 
                    - carte 
                    - user 
                    - abonneCarte
                    - createdAt
                    - paymentInstruction
        PaymentInstruction:
            class: JMS\Payment\CoreBundle\Entity\PaymentInstruction
            disabled_actions: ['new']
            show: 
                fields:
                    - id
                    - approvedAmount
                    - approvingAmount
                    - createdAt
                    - currency
                    - paymentSystemName
                    - { property: paymentInstruction, label: 'Status du paiement', template: 'field_payment.html.twig' }
            list:
                fields:
                    - id
                    - approvedAmount
                    - approvingAmount
                    - createdAt
                    - currency
                    - paymentSystemName
                    - { property: paymentInstruction, label: 'Status du paiement', template: 'field_payment.html.twig' }
#        Payment:
#            class: JMS\Payment\CoreBundle\Entity\Payment
#            disabled_action: ['new']
            
        ###
        # Partner
        ###
        Partner:
            class: AppBundle\Entity\User\Partner\Partner
            disabled_actions: ['new','delete']
            list: 
                fields: 
                    - id
                    - username
                    - email
                    - enabled
                    - enabledByAdmin
                    - { property: phoneMobile, template: 'field_phone.html.twig' }
                    - { property: phoneFixed, template: 'field_phone.html.twig' }
                    - lastLogin
            show:        
                fields: 
                    - id
                    - username
                    - email
                    - enabled
                    - enabledByAdmin
                    - { property: phoneMobile, template: 'field_phone.html.twig' }
                    - { property: phoneFixed, template: 'field_phone.html.twig' }
                    - lastLogin
        Company: 
            class: AppBundle\Entity\User\Partner\Company
            disabled_actions: ['new','delete']
            list:
                fields: 
                    - id 
                    - name 
                    - about 
                    - partner
                    - address
                    - { property: logo.name, type: 'image', base_path: '%app.media.company.logo%' }
                    - category
        Offre:
            class: AppBundle\Entity\User\Partner\Offre
            disabled_actions: ['new','delete']
            list:
                fields: 
                    - id 
                    - name
                    - about 
                    - start
                    - end
                    - company
                    - { property: category.name, label: 'Type de réduction'}
                    - { property: offreDomain.name, label: 'Catégorie' }
                    - { property: featured.name, label: 'Image de l''offre', type: image, base_path: '%app.media.offre.featured%'}
                    - howEnjoy
        ###
        # Admin
        ###
        Admin:
            class: AppBundle\Entity\User\Admin
            disabled_actions: ['delete']
            list: 
                fields: [id, username, email, enabled, enabledByAdmin, lastLogin]