<?php

namespace AppBundle\Repository\Admin\Category;

use AppBundle\Repository\RepositoryTrait;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
    
    const ALIAS = 'c';
    
    public function findAllForHomePage()
    {
        $qb     = $this->createQueryBuilder(self::ALIAS);
    }
    
    ###
    # Join
    ###
    
}
