<?php

namespace AppBundle\Repository\Admin\Category;

use Doctrine\ORM\QueryBuilder;
use AppBundle\Repository\RepositoryTrait;

/**
 * OffreDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreDomainRepository extends \Doctrine\ORM\EntityRepository
{
    const ALIAS     = 'o';
    
    use RepositoryTrait;
    
    public function findAllForHomePage()
    {
        $qb     = $this->createQueryBuilder(self::ALIAS);
        
        $this->joinWithOffres($qb);
        
        return $qb->getQuery()->getResult();
    }
    
    ###
    # Join 
    ###
    
    public function joinWithOffres(QueryBuilder $qb)
    {
        $qb
            ->leftJoin(self::ALIAS . '.offres', 'offre')
            ->addSelect('offre')
            ->leftJoin('offre.featured', 'featured')
            ->addSelect('featured')
            ->leftJoin('offre.company', 'company')
            ->addSelect('company')
          ;
        
        return $qb;
    }
}
