<?php

namespace AppBundle\Repository\Admin\Category;

use AppBundle\Repository\RepositoryTrait;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    const ALIAS = 'o';
    
    use RepositoryTrait;
    
    public function findAllForHomePage()
    {
        $qb     = $this->createQueryBuilder(self::ALIAS);
        
        $this->joinWithOffres($qb);
        
        return $qb->getQuery()->getResult();
    }
    
    
}
