<?php

namespace AppBundle\Repository\Admin\Category;

use AppBundle\Repository\RepositoryTrait;

/**
 * OffreDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreDomainRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
