###
# Carte
###
page_carte_index:
    path: /cartes
    defaults: { _controller: AppBundle:Front\Pages\Carte:index }
    methods: [GET] 
    
pages_index:
    path: /{slug}
    defaults: { _controller: AppBundle:Front\Pages\Page:index }
    prefix: /pages