admin_category_carte:
    resource: "@AppBundle/Resources/config/routing/admin/category/carte.yml"
    prefix: /carte
    
admin_category_offre:
    resource: "@AppBundle/Resources/config/routing/admin/category/offre.yml"
    prefix: /offre
    
admin_category_compagny:
    resource: "@AppBundle/Resources/config/routing/admin/category/compagny.yml"
    prefix: /compagny