
category_carte_index:
    path:     /
    defaults: { _controller: AppBundle:Admin\Carte:index }

category_carte_new:
    path:     /new
    defaults: { _controller: AppBundle:Admin\Carte:new }

category_carte_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Admin\Carte:delete }
    requirements:
        id: '\d+'

category_carte_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:Admin\Carte:update }
    requirements:
        id: '\d+'
