
category_company_index:
    path:     /
    defaults: { _controller: AppBundle:Admin\Category\Company:index }

category_company_new:
    path:     /new
    defaults: { _controller: AppBundle:Admin\Category\Company:new }

category_company_delete:
    path:     /delete/{id}
    defaults: { _controller: AppBundle:Admin\Category\Company:delete }
    requirements:
        id: '\d+'

category_company_update:
    path:     /update/{id}
    defaults: { _controller: AppBundle:Admin\Category\Company:update }
    requirements:
        id: '\d+'
