<?php

namespace AppBundle\Repository\User\Partner;

use AppBundle\Repository\RepositoryTrait;

/**
 * FeaturedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
