<?php

namespace AppBundle\Repository\User\Partner;

use AppBundle\Repository\RepositoryTrait;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends \Doctrine\ORM\EntityRepository
{
    use RepositoryTrait;
}
