# front/partner/all
partner:
    resource: "@AppBundle/Resources/config/routing/front/partner/partner.yml"
    
company:
    resource: "@AppBundle/Resources/config/routing/front/partner/company.yml"

offre:
    resource: "@AppBundle/Resources/config/routing/front/partner/offre.yml"