user_partner_index:
    path: /{partner}
    defaults: { _controller: AppBundle:Front\Partner\Partner:show }
    methods: [GET]

user_partner_show:
    path: /{partner}
    defaults: { _controller: AppBundle:Front\Partner\Partner:show }
    methods: [GET]

user_partner_update:
    path: /{partner}/update
    defaults: { _controller: AppBundle:Front\Partner\Partner:update }
    methods: [GET,POST]
    
user_partner_edit_parameters:
    path: /{partner}/parameters
    defaults: { _controller: AppBundle:Front\Partner\Parameters:update }
    methods: [GET,POST]    